import { User, Category, Product, Client, Invoice, StockMovement, ActivityLog } from './types';

export const mockUsers: User[] = [
  {
    id: '1',
    name: 'Administrador',
    email: 'admin@empresa.com',
    role: 'admin',
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '2',
    name: 'Usuario Vendedor',
    email: 'vendedor@empresa.com',
    role: 'user',
    createdAt: new Date('2024-01-15'),
  },
];

export const mockCategories: Category[] = [
  {
    id: '1',
    name: 'Electrónicos',
    description: 'Productos electrónicos y tecnología',
    createdAt: new Date('2024-01-01'),
    createdBy: '1',
    updatedAt: new Date('2024-01-01'),
    updatedBy: '1',
  },
  {
    id: '2',
    name: 'Ropa',
    description: 'Vestimenta y accesorios',
    createdAt: new Date('2024-01-01'),
    createdBy: '1',
    updatedAt: new Date('2024-01-01'),
    updatedBy: '1',
  },
  {
    id: '3',
    name: 'Hogar',
    description: 'Artículos para el hogar',
    createdAt: new Date('2024-01-01'),
    createdBy: '1',
    updatedAt: new Date('2024-01-01'),
    updatedBy: '1',
  },
];

export const mockProducts: Product[] = [
  {
    id: '1',
    code: 'PRD001',
    name: 'Laptop HP Pavilion',
    description: 'Laptop HP Pavilion 15.6" Intel Core i5',
    price: 120000,
    stock: 5,
    minStock: 2,
    categories: ['1'],
    createdAt: new Date('2024-01-01'),
    createdBy: '1',
    updatedAt: new Date('2024-01-01'),
    updatedBy: '1',
  },
  {
    id: '2',
    code: 'PRD002',
    name: 'Mouse Inalámbrico',
    description: 'Mouse inalámbrico Logitech M185',
    price: 2500,
    stock: 1,
    minStock: 5,
    categories: ['1'],
    createdAt: new Date('2024-01-01'),
    createdBy: '1',
    updatedAt: new Date('2024-01-01'),
    updatedBy: '1',
  },
  {
    id: '3',
    code: 'PRD003',
    name: 'Camisa de Algodón',
    description: 'Camisa de algodón 100% talla M',
    price: 8500,
    stock: 15,
    minStock: 10,
    categories: ['2'],
    createdAt: new Date('2024-01-01'),
    createdBy: '1',
    updatedAt: new Date('2024-01-01'),
    updatedBy: '1',
  },
  {
    id: '4',
    code: 'PRD004',
    name: 'Lámpara de Mesa',
    description: 'Lámpara de mesa LED ajustable',
    price: 3500,
    stock: 8,
    minStock: 5,
    categories: ['3'],
    createdAt: new Date('2024-01-01'),
    createdBy: '1',
    updatedAt: new Date('2024-01-01'),
    updatedBy: '1',
  },
];

export const mockClients: Client[] = [
  {
    id: '1',
    documentType: 'CUIT',
    documentNumber: '30712293841',
    businessName: 'Empresa Ejemplo SRL',
    email: 'contacto@empresaejemplo.com',
    address: 'Av. Siempre Viva 742, CABA',
    province: 'Buenos Aires',
    phone: '011-1234-5678',
    createdAt: new Date('2024-01-01'),
    createdBy: '1',
    updatedAt: new Date('2024-01-01'),
    updatedBy: '1',
  },
  {
    id: '2',
    documentType: 'DNI',
    documentNumber: '12345678',
    businessName: 'Juan Pérez',
    email: 'juan.perez@email.com',
    address: 'Calle Falsa 123, Rosario',
    province: 'Santa Fe',
    phone: '0341-987-6543',
    createdAt: new Date('2024-01-15'),
    createdBy: '1',
    updatedAt: new Date('2024-01-15'),
    updatedBy: '1',
  },
  {
    id: '3',
    documentType: 'CUIT',
    documentNumber: '20123456789',
    businessName: 'Comercio del Norte SA',
    email: 'ventas@comerciodelnorte.com',
    address: 'Ruta 9 Km 500, Córdoba',
    province: 'Córdoba',
    phone: '0351-456-7890',
    createdAt: new Date('2024-02-01'),
    createdBy: '1',
    updatedAt: new Date('2024-02-01'),
    updatedBy: '1',
  },
];

export const mockInvoices: Invoice[] = [
  {
    id: '1',
    type: 'A',
    number: '0001-00000001',
    clientId: '1',
    client: mockClients[0],
    items: [
      {
        productId: '1',
        code: 'PRD001',
        description: 'Laptop HP Pavilion',
        quantity: 1,
        unitPrice: 120000,
        iva: 21,
        discount: 0,
        total: 145200,
      },
      {
        productId: '2',
        code: 'PRD002',
        description: 'Mouse Inalámbrico',
        quantity: 2,
        unitPrice: 2500,
        iva: 21,
        discount: 500,
        total: 5500,
      },
    ],
    subtotal: 125000,
    iva: 26250,
    total: 151250,
    status: 'issued',
    issuedAt: new Date('2024-06-20'),
    createdAt: new Date('2024-06-20'),
    createdBy: '1',
    updatedAt: new Date('2024-06-20'),
    updatedBy: '1',
  },
  {
    id: '2',
    type: 'B',
    number: '0001-00000002',
    clientId: '2',
    client: mockClients[1],
    items: [
      {
        productId: '3',
        code: 'PRD003',
        description: 'Camisa de Algodón',
        quantity: 3,
        unitPrice: 8500,
        iva: 21,
        discount: 0,
        total: 30855,
      },
    ],
    subtotal: 25500,
    iva: 5355,
    total: 30855,
    status: 'issued',
    issuedAt: new Date('2024-06-21'),
    createdAt: new Date('2024-06-21'),
    createdBy: '2',
    updatedAt: new Date('2024-06-21'),
    updatedBy: '2',
  },
];

export const mockStockMovements: StockMovement[] = [
  {
    id: '1',
    productId: '1',
    product: mockProducts[0],
    type: 'in',
    quantity: 10,
    reason: 'Compra inicial',
    reference: 'OC-001',
    createdAt: new Date('2024-01-01'),
    createdBy: '1',
  },
  {
    id: '2',
    productId: '1',
    product: mockProducts[0],
    type: 'out',
    quantity: 1,
    reason: 'Venta',
    reference: 'FAC-001',
    createdAt: new Date('2024-06-20'),
    createdBy: '1',
  },
  {
    id: '3',
    productId: '2',
    product: mockProducts[1],
    type: 'in',
    quantity: 20,
    reason: 'Reposición de stock',
    reference: 'OC-002',
    createdAt: new Date('2024-06-15'),
    createdBy: '1',
  },
  {
    id: '4',
    productId: '2',
    product: mockProducts[1],
    type: 'out',
    quantity: 2,
    reason: 'Venta',
    reference: 'FAC-001',
    createdAt: new Date('2024-06-20'),
    createdBy: '1',
  },
];

export const mockActivityLogs: ActivityLog[] = [
  {
    id: '1',
    userId: '1',
    user: mockUsers[0],
    action: 'create',
    entity: 'product',
    entityId: '1',
    details: 'Producto Laptop HP Pavilion creado',
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '2',
    userId: '1',
    user: mockUsers[0],
    action: 'create',
    entity: 'client',
    entityId: '1',
    details: 'Cliente Empresa Ejemplo SRL creado',
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '3',
    userId: '1',
    user: mockUsers[0],
    action: 'create',
    entity: 'invoice',
    entityId: '1',
    details: 'Factura A 0001-00000001 creada',
    createdAt: new Date('2024-06-20'),
  },
  {
    id: '4',
    userId: '2',
    user: mockUsers[1],
    action: 'create',
    entity: 'invoice',
    entityId: '2',
    details: 'Factura B 0001-00000002 creada',
    createdAt: new Date('2024-06-21'),
  },
]; 